// 82 words × full detail — seed via: npm run seed:details
export interface WordDetailData {
  word: string
  lang: 'en' | 'th'
  exampleTh: string
  exampleEn: string
  severityExplanation: string
  canUseWith: string[]
  neverUseWith: string[]
  alternatives: string[]
  impactDescription: string
  hasDangerFlag: boolean
}

export const wordDetailData: WordDetailData[] = [
  // ─── EN Level 1 — Polite ────────────────────────────────────────────────────
  {
    word: 'please', lang: 'en',
    exampleTh: '"กรุณาส่งดินสอให้หน่อยได้ไหม?" — ทำให้คำขอฟังดูดีและสุภาพ',
    exampleEn: '"Can you please pass me the pencil?"',
    severityExplanation: 'คำสุภาพที่ทุกคนใช้ได้ ทำให้อีกฝ่ายรู้สึกดีและอยากช่วย',
    canUseWith: ['friends', 'teachers', 'parents', 'strangers'],
    neverUseWith: [],
    alternatives: [],
    impactDescription: 'ทำให้คนรู้สึกอยากช่วยเหลือ และสร้างบรรยากาศที่ดี',
    hasDangerFlag: false,
  },
  {
    word: 'thank you', lang: 'en',
    exampleTh: '"ขอบคุณที่ช่วยหยิบของให้!" — แสดงความซาบซึ้งใจต่ออีกฝ่าย',
    exampleEn: '"Thank you for helping me pick that up!"',
    severityExplanation: 'คำแสดงความขอบคุณ ทำให้อีกฝ่ายรู้สึกว่าความพยายามของเขาได้รับการยอมรับ',
    canUseWith: ['everyone'],
    neverUseWith: [],
    alternatives: [],
    impactDescription: 'สร้างความสัมพันธ์ที่ดีและทำให้คนรู้สึกมีคุณค่า',
    hasDangerFlag: false,
  },
  {
    word: 'sorry', lang: 'en',
    exampleTh: '"ขอโทษที่ชนเข้านะ ไม่ได้ตั้งใจ" — รับผิดชอบต่อสิ่งที่เกิดขึ้น',
    exampleEn: '"Sorry, I didn\'t mean to bump into you."',
    severityExplanation: 'คำขอโทษที่จริงใจ ช่วยซ่อมแซมความสัมพันธ์เมื่อทำผิดพลาด',
    canUseWith: ['friends', 'teachers', 'parents', 'strangers'],
    neverUseWith: [],
    alternatives: ['I apologize', 'I didn\'t mean to', 'my bad'],
    impactDescription: 'ช่วยลดความขัดแย้งและแสดงว่าเราใส่ใจความรู้สึกของคนอื่น',
    hasDangerFlag: false,
  },
  {
    word: 'excuse me', lang: 'en',
    exampleTh: '"ขอโทษนะ ขอผ่านหน่อยได้ไหม?" — ใช้เมื่อต้องการผ่านหรือขอความสนใจ',
    exampleEn: '"Excuse me, could I get past please?"',
    severityExplanation: 'คำสุภาพเพื่อขอทางหรือเรียกความสนใจโดยไม่รบกวน',
    canUseWith: ['everyone'],
    neverUseWith: [],
    alternatives: ['pardon me', 'may I pass', 'could I get by'],
    impactDescription: 'แสดงให้เห็นว่าเราเคารพพื้นที่และเวลาของคนอื่น',
    hasDangerFlag: false,
  },
  {
    word: 'you\'re welcome', lang: 'en',
    exampleTh: '"ยินดีเลย ไม่ต้องเกรงใจ!" — ตอบรับคำขอบคุณอย่างสุภาพ',
    exampleEn: '"You\'re welcome! Happy to help."',
    severityExplanation: 'คำตอบสุภาพเมื่อมีคนขอบคุณ แสดงว่าช่วยด้วยความยินดี',
    canUseWith: ['everyone'],
    neverUseWith: [],
    alternatives: ['no problem', 'anytime', 'happy to help', 'of course'],
    impactDescription: 'ทำให้อีกฝ่ายรู้สึกว่าไม่เป็นภาระและความช่วยเหลือนั้นมาจากใจ',
    hasDangerFlag: false,
  },
  {
    word: 'pardon me', lang: 'en',
    exampleTh: '"ขอโทษ ช่วยพูดซ้ำอีกทีได้ไหม?" — สุภาพเมื่อไม่ได้ยินหรือขอทาง',
    exampleEn: '"Pardon me, could you repeat that?"',
    severityExplanation: 'คำสุภาพมากเมื่อต้องขอให้พูดซ้ำหรือต้องการผ่าน',
    canUseWith: ['teachers', 'adults', 'strangers', 'friends'],
    neverUseWith: [],
    alternatives: ['excuse me', 'sorry?', 'could you say that again'],
    impactDescription: 'แสดงความสุภาพและความใส่ใจในการสื่อสาร',
    hasDangerFlag: false,
  },
  {
    word: 'well done', lang: 'en',
    exampleTh: '"เยี่ยมมาก! เธอทำได้ดีมากในการแข่งขันครั้งนี้!"',
    exampleEn: '"Well done! You did a great job in the competition!"',
    severityExplanation: 'คำชมเชยที่ให้กำลังใจและทำให้อีกฝ่ายรู้สึกภูมิใจ',
    canUseWith: ['friends', 'classmates', 'siblings'],
    neverUseWith: [],
    alternatives: ['great job', 'you nailed it', 'I\'m proud of you', 'amazing'],
    impactDescription: 'ช่วยให้คนรู้สึกมีคุณค่าและมีแรงบันดาลใจทำสิ่งดีต่อไป',
    hasDangerFlag: false,
  },
  {
    word: 'good job', lang: 'en',
    exampleTh: '"ทำงานได้ดีมากนะ ขอบคุณที่ช่วย!"',
    exampleEn: '"Good job finishing that on time!"',
    severityExplanation: 'คำชมที่เป็นมิตร เหมาะทุกสถานการณ์',
    canUseWith: ['everyone'],
    neverUseWith: [],
    alternatives: ['nice work', 'well done', 'you did great', 'I\'m impressed'],
    impactDescription: 'กระตุ้นให้คนรู้สึกดีและอยากทำสิ่งดีต่อไป',
    hasDangerFlag: false,
  },
  {
    word: 'bless you', lang: 'en',
    exampleTh: '"สุขภาพดีด้วยนะ!" — พูดเมื่อมีคนจาม',
    exampleEn: '"Bless you!" (after someone sneezes)',
    severityExplanation: 'คำแสดงความห่วงใยเล็กน้อย ช่วยสร้างบรรยากาศที่อบอุ่น',
    canUseWith: ['everyone'],
    neverUseWith: [],
    alternatives: ['gesundheit', 'are you okay?'],
    impactDescription: 'แสดงว่าเราสังเกตเห็นและใส่ใจคนอื่น',
    hasDangerFlag: false,
  },

  // ─── EN Level 2 — Rude ──────────────────────────────────────────────────────
  {
    word: 'shut up', lang: 'en',
    exampleTh: '"หุบปากซะ!" — บอกให้หยุดพูดอย่างหยาบคาย ทำให้อีกฝ่ายเจ็บปวด',
    exampleEn: '"Shut up!" (yelled at a friend)',
    severityExplanation: 'ไม่สุภาพ ทำให้คนรู้สึกถูกปฏิเสธและไม่มีคุณค่า',
    canUseWith: [],
    neverUseWith: ['friends', 'teachers', 'parents', 'strangers'],
    alternatives: ['please be quiet', 'could you lower your voice?', 'I need a moment of quiet'],
    impactDescription: 'ทำให้คนรู้สึกอับอาย โกรธ และไม่อยากพูดคุยอีก',
    hasDangerFlag: false,
  },
  {
    word: 'whatever', lang: 'en',
    exampleTh: '"ก็ได้..." — ตอบเย็นชา แสดงว่าไม่สนใจ ทำให้อีกฝ่ายรู้สึกถูกดูถูก',
    exampleEn: '"Whatever, I don\'t care." (dismissively)',
    severityExplanation: 'แสดงถึงการไม่ให้ความสำคัญกับอีกฝ่าย ทำให้รู้สึกว่าถูกมองข้าม',
    canUseWith: [],
    neverUseWith: ['teachers', 'parents', 'friends who are upset'],
    alternatives: ['okay, I understand', 'let\'s talk about it later', 'I hear you'],
    impactDescription: 'ทำให้อีกฝ่ายรู้สึกไม่มีคุณค่าและไม่ได้รับการรับฟัง',
    hasDangerFlag: false,
  },
  {
    word: 'dumb', lang: 'en',
    exampleTh: '"เธอโง่มากนะ!" — ดูถูกความฉลาดของคนอื่น',
    exampleEn: '"That\'s such a dumb idea!"',
    severityExplanation: 'ดูถูกความสามารถของคน ทำให้รู้สึกอับอายและไม่มั่นใจ',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['I think there\'s a better way', 'maybe we could try differently', 'let me explain'],
    impactDescription: 'ทำให้คนรู้สึกอับอายและกลัวที่จะแสดงความคิดเห็น',
    hasDangerFlag: false,
  },
  {
    word: 'liar', lang: 'en',
    exampleTh: '"แกโกหก!" — กล่าวหาว่าคนโกหกโดยตรง อาจไม่จริงและทำร้ายความรู้สึก',
    exampleEn: '"You\'re such a liar!"',
    severityExplanation: 'เป็นการกล่าวหาที่ทำร้ายความน่าเชื่อถือของคน',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['I don\'t think that\'s true', 'can you explain that again?', 'I\'m not sure I believe that'],
    impactDescription: 'ทำลายความไว้วางใจและทำให้ความสัมพันธ์แตกหัก',
    hasDangerFlag: false,
  },
  {
    word: 'annoying', lang: 'en',
    exampleTh: '"เธอน่ารำคาญมากเลย!" — ทำให้คนรู้สึกว่าตัวเองรบกวนคนอื่น',
    exampleEn: '"You\'re so annoying!"',
    severityExplanation: 'ดูถูกพฤติกรรมของคน ทำให้รู้สึกว่าตัวเองไม่เป็นที่ต้องการ',
    canUseWith: [],
    neverUseWith: ['friends', 'classmates'],
    alternatives: ['I need some space', 'I\'m feeling overwhelmed right now', 'can we talk later?'],
    impactDescription: 'ทำให้คนรู้สึกถูกปฏิเสธและไม่มั่นใจในตัวเอง',
    hasDangerFlag: false,
  },
  {
    word: 'gross', lang: 'en',
    exampleTh: '"น่าขยะแขยง!" — แสดงความรังเกียจต่อคนหรือสิ่งของ',
    exampleEn: '"Ew, that\'s so gross!"',
    severityExplanation: 'แสดงความรังเกียจ ทำให้คนรู้สึกว่าตัวเองไม่เป็นที่ยอมรับ',
    canUseWith: [],
    neverUseWith: ['others about people\'s appearance or food'],
    alternatives: ['that\'s not for me', 'I prefer something else', 'that\'s a bit much for me'],
    impactDescription: 'ทำให้คนรู้สึกอับอายและไม่เป็นที่ยอมรับ',
    hasDangerFlag: false,
  },
  {
    word: 'shut it', lang: 'en',
    exampleTh: '"หุบปากซะ!" — คล้าย shut up แต่ฟังดูก้าวร้าวกว่า',
    exampleEn: '"Just shut it, will you?"',
    severityExplanation: 'ไม่สุภาพและก้าวร้าว สั่งให้คนหยุดพูดในแบบหยาบคาย',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['please be quiet', 'I need quiet time', 'could we talk later?'],
    impactDescription: 'ทำให้อีกฝ่ายรู้สึกถูกข่มขู่และไม่ได้รับการเคารพ',
    hasDangerFlag: false,
  },
  {
    word: 'weirdo', lang: 'en',
    exampleTh: '"ไอ้แปลก!" — ดูถูกความเป็นตัวของคนที่แตกต่างจากคนอื่น',
    exampleEn: '"You\'re such a weirdo!"',
    severityExplanation: 'ดูถูกความแตกต่างของคน ทำให้รู้สึกว่าตัวเองผิดปกติ',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['you\'re unique', 'you\'re interesting', 'that\'s a different way to think about it'],
    impactDescription: 'ทำให้คนกลัวที่จะเป็นตัวเองและรู้สึกแปลกแยก',
    hasDangerFlag: false,
  },
  {
    word: 'buzz off', lang: 'en',
    exampleTh: '"ไปให้พ้น!" — บอกให้คนออกไปจากบริเวณนั้นอย่างหยาบคาย',
    exampleEn: '"Buzz off, I\'m busy!"',
    severityExplanation: 'ไม่สุภาพ ปฏิเสธคนอื่นอย่างดูถูก',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['I need some time alone', 'I\'m busy right now', 'can we talk later?'],
    impactDescription: 'ทำให้อีกฝ่ายรู้สึกถูกปฏิเสธและไม่มีคุณค่า',
    hasDangerFlag: false,
  },

  // ─── EN Level 3 — Coarse ────────────────────────────────────────────────────
  {
    word: 'stupid', lang: 'en',
    exampleTh: '"โง่มากเลย!" — ดูถูกความฉลาดอย่างรุนแรง ทำร้ายความรู้สึกมาก',
    exampleEn: '"That was such a stupid mistake!"',
    severityExplanation: 'ดูถูกความฉลาดอย่างรุนแรง ทำให้คนรู้สึกอับอายและไม่มั่นใจในตัวเอง',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['that didn\'t work out', 'let\'s think of a better way', 'everyone makes mistakes'],
    impactDescription: 'ทำลายความมั่นใจและทำให้คนกลัวที่จะลองสิ่งใหม่',
    hasDangerFlag: false,
  },
  {
    word: 'idiot', lang: 'en',
    exampleTh: '"ไอ้โง่!" — เรียกคนว่าโง่เขลาอย่างดูถูกและรุนแรง',
    exampleEn: '"You idiot, why did you do that?"',
    severityExplanation: 'คำดูถูกรุนแรงที่ทำลายศักดิ์ศรีของคน',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['that\'s not the best approach', 'next time let\'s try this instead', 'it\'s okay, let\'s fix it'],
    impactDescription: 'ทำให้คนรู้สึกอับอายอย่างรุนแรงและสูญเสียความมั่นใจ',
    hasDangerFlag: false,
  },
  {
    word: 'loser', lang: 'en',
    exampleTh: '"ไอ้ขี้แพ้!" — ดูถูกคนที่แพ้หรือทำสิ่งผิดพลาด',
    exampleEn: '"You\'re such a loser!"',
    severityExplanation: 'ดูถูกคนว่าล้มเหลว ทำให้รู้สึกว่าตัวเองไม่มีคุณค่า',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['better luck next time', 'you\'ll get it', 'keep trying'],
    impactDescription: 'ทำให้คนรู้สึกว่าความพ่ายแพ้นั้นกำหนดความเป็นตัวเขา',
    hasDangerFlag: false,
  },
  {
    word: 'ugly', lang: 'en',
    exampleTh: '"น่าเกลียดจัง!" — ดูถูกรูปลักษณ์ของคน ทำร้ายจิตใจอย่างรุนแรง',
    exampleEn: '"You\'re so ugly!"',
    severityExplanation: 'ดูถูกรูปลักษณ์ที่คนควบคุมไม่ได้ ทำให้รู้สึกอับอายในสิ่งที่ตัวเองเป็น',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['everyone looks different', 'beauty comes in all forms', 'I like how you look'],
    impactDescription: 'ทำให้คนรู้สึกไม่มั่นใจในรูปลักษณ์และอาจนำไปสู่ปัญหาภาพลักษณ์',
    hasDangerFlag: false,
  },
  {
    word: 'fat', lang: 'en',
    exampleTh: '"อ้วนมากเลย!" — ดูถูกน้ำหนักหรือร่างกายของคน',
    exampleEn: '"You\'re so fat!"',
    severityExplanation: 'ดูถูกร่างกายของคน ทำร้ายความมั่นใจอย่างรุนแรงและอาจนำไปสู่ปัญหาสุขภาพจิต',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['everyone\'s body is different', 'health matters more than size', 'you look great'],
    impactDescription: 'อาจทำให้เกิดปัญหาความนับถือตนเองและปัญหาการกินในระยะยาว',
    hasDangerFlag: false,
  },
  {
    word: 'jerk', lang: 'en',
    exampleTh: '"แกเป็นคนแย่มากเลย!" — เรียกคนว่าเลวหรือไม่ดี',
    exampleEn: '"Don\'t be such a jerk!"',
    severityExplanation: 'เรียกคนว่าเลวหรือมีพฤติกรรมไม่ดี ทำร้ายความสัมพันธ์',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['that wasn\'t kind', 'please treat me with respect', 'can we talk about this?'],
    impactDescription: 'ทำลายความสัมพันธ์และทำให้คนรู้สึกว่าตัวเองเป็นคนเลว',
    hasDangerFlag: false,
  },
  {
    word: 'moron', lang: 'en',
    exampleTh: '"ไอ้โง่เขลา!" — ดูถูกความฉลาดอย่างรุนแรงมาก',
    exampleEn: '"What a moron!"',
    severityExplanation: 'คำดูถูกที่รุนแรงกว่า stupid หรือ dumb ทำร้ายจิตใจอย่างมาก',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['let\'s think this through together', 'maybe there\'s a better way', 'I can help you with this'],
    impactDescription: 'ทำลายความมั่นใจและทำให้คนรู้สึกว่าตัวเองไร้ความสามารถ',
    hasDangerFlag: false,
  },
  {
    word: 'pathetic', lang: 'en',
    exampleTh: '"น่าสมเพชมาก!" — แสดงความดูถูกเหยียดหยามคน',
    exampleEn: '"That\'s pathetic!"',
    severityExplanation: 'แสดงความดูถูกและไม่นับถือคน ทำให้รู้สึกว่าตัวเองน้อยกว่าคนอื่น',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['I think you can do better', 'that\'s a tough situation', 'keep going'],
    impactDescription: 'ทำให้คนรู้สึกสูญเสียศักดิ์ศรีและหมดกำลังใจ',
    hasDangerFlag: false,
  },
  {
    word: 'useless', lang: 'en',
    exampleTh: '"ไร้ประโยชน์มากเลย!" — ดูถูกว่าคนไม่มีคุณค่าหรือความสามารถ',
    exampleEn: '"You\'re completely useless!"',
    severityExplanation: 'บอกว่าคนไม่มีคุณค่า ทำลายความมั่นใจอย่างรุนแรง',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['let me help you with that', 'you contribute in different ways', 'everyone has strengths'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองไม่มีประโยชน์ต่อโลกใบนี้',
    hasDangerFlag: false,
  },

  // ─── EN Level 4 — Harsh ─────────────────────────────────────────────────────
  {
    word: 'hate you', lang: 'en',
    exampleTh: '"เกลียดแกมาก!" — แสดงความเกลียดชังโดยตรง ทำร้ายจิตใจอย่างรุนแรง',
    exampleEn: '"I hate you!"',
    severityExplanation: 'แสดงความเกลียดชังอย่างรุนแรง ทำให้คนรู้สึกว่าไม่เป็นที่รัก',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['I\'m really upset with you', 'I need space right now', 'what you did hurt me'],
    impactDescription: 'ทำให้คนรู้สึกถูกปฏิเสธและไม่เป็นที่ต้องการ อาจก่อให้เกิดความเจ็บปวดระยะยาว',
    hasDangerFlag: true,
  },
  {
    word: 'freak', lang: 'en',
    exampleTh: '"ไอ้ประหลาด!" — เรียกคนว่าผิดปกติหรือน่ากลัว',
    exampleEn: '"You\'re such a freak!"',
    severityExplanation: 'ดูถูกความแตกต่างของคนอย่างรุนแรง ทำให้รู้สึกแปลกแยกจากสังคม',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['you\'re unique', 'being different is okay', 'I want to understand you better'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองผิดปกติและไม่เป็นที่ยอมรับในสังคม',
    hasDangerFlag: true,
  },
  {
    word: 'creep', lang: 'en',
    exampleTh: '"แกทำให้กลัวมากเลย / น่าขนลุก!" — เรียกคนว่าน่ากลัวหรือน่าขนลุก',
    exampleEn: '"You\'re such a creep!"',
    severityExplanation: 'เรียกคนว่าน่ากลัวหรือมีพฤติกรรมไม่เหมาะสม ทำให้รู้สึกแปลกแยก',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['that behavior makes me uncomfortable', 'please give me space', 'I\'d like you to stop that'],
    impactDescription: 'ทำให้คนรู้สึกอับอายและถูกปฏิเสธจากสังคม',
    hasDangerFlag: true,
  },
  {
    word: 'go die', lang: 'en',
    exampleTh: '"ไปตายซะ!" — บอกให้คนไปตาย อันตรายมากและอาจทำให้คนทำร้ายตัวเอง',
    exampleEn: '"Go die!"',
    severityExplanation: 'อันตรายมาก บอกให้คนตายซึ่งอาจกระตุ้นให้เกิดความคิดฆ่าตัวตาย',
    canUseWith: [],
    neverUseWith: ['everyone — never say this'],
    alternatives: ['I\'m really angry right now', 'I need to walk away', 'let\'s talk when I\'ve calmed down'],
    impactDescription: 'อาจทำให้คนคิดทำร้ายตัวเองและเป็นการคุกคามที่อันตรายมาก',
    hasDangerFlag: true,
  },
  {
    word: 'worthless', lang: 'en',
    exampleTh: '"แกไม่มีคุณค่าเลย!" — ดูถูกคนว่าไม่มีความสำคัญ',
    exampleEn: '"You\'re completely worthless!"',
    severityExplanation: 'บอกว่าคนไม่มีคุณค่าเลย ทำลายความมั่นใจในตัวเองอย่างสมบูรณ์',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['I\'m frustrated', 'you matter to people', 'everyone has value'],
    impactDescription: 'ทำให้คนรู้สึกว่าชีวิตไม่มีความหมาย อาจนำไปสู่ภาวะซึมเศร้า',
    hasDangerFlag: true,
  },
  {
    word: 'get lost', lang: 'en',
    exampleTh: '"ไปให้พ้นหน้าฉัน!" — ไล่คนออกไปอย่างรุนแรงและดูถูก',
    exampleEn: '"Just get lost!"',
    severityExplanation: 'ปฏิเสธคนอย่างรุนแรงและดูถูก ทำให้รู้สึกถูกทอดทิ้ง',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['I need time alone', 'let\'s talk later', 'I need some space right now'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองไม่เป็นที่ต้องการและถูกทอดทิ้ง',
    hasDangerFlag: true,
  },
  {
    word: 'nobody likes you', lang: 'en',
    exampleTh: '"ไม่มีใครชอบแกเลย!" — บอกคนว่าไม่มีใครสนใจหรือชอบเขา',
    exampleEn: '"Nobody likes you!"',
    severityExplanation: 'ทำให้คนรู้สึกโดดเดี่ยวและไม่เป็นที่ยอมรับในสังคม',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['I\'m upset with you', 'we had a misunderstanding', 'let\'s work this out'],
    impactDescription: 'ทำให้คนรู้สึกโดดเดี่ยวอย่างสุดขีด อาจนำไปสู่ปัญหาสุขภาพจิตรุนแรง',
    hasDangerFlag: true,
  },
  {
    word: 'you suck', lang: 'en',
    exampleTh: '"แกห่วยมากเลย!" — ดูถูกความสามารถหรือตัวตนของคนอย่างรุนแรง',
    exampleEn: '"You suck at this!"',
    severityExplanation: 'ดูถูกคนหรือความสามารถของเขาอย่างรุนแรงและหยาบคาย',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['that was tough', 'you\'ll improve with practice', 'let\'s try a different approach'],
    impactDescription: 'ทำลายความมั่นใจและทำให้คนไม่อยากพยายามต่อไป',
    hasDangerFlag: true,
  },
  {
    word: 'shut your mouth', lang: 'en',
    exampleTh: '"ปิดปากซะ!" — คำสั่งให้หยุดพูดอย่างรุนแรงและก้าวร้าว',
    exampleEn: '"Shut your mouth!"',
    severityExplanation: 'คำสั่งที่ก้าวร้าวและดูถูก ทำให้อีกฝ่ายรู้สึกถูกข่มขู่',
    canUseWith: [],
    neverUseWith: ['everyone'],
    alternatives: ['please stop', 'I need quiet', 'let me speak for a moment'],
    impactDescription: 'ทำให้คนรู้สึกถูกข่มขู่และไม่กล้าพูดในอนาคต',
    hasDangerFlag: true,
  },

  // ─── EN Level 5 — Dangerous ─────────────────────────────────────────────────
  {
    word: 'kill you', lang: 'en',
    exampleTh: '"จะฆ่าแก!" — ขู่ฆ่า เป็นอาชญากรรม ต้องแจ้งผู้ใหญ่ทันที',
    exampleEn: '"I\'ll kill you!"',
    severityExplanation: 'เป็นการขู่ฆ่าซึ่งเป็นความผิดทางกฎหมาย ทำให้ผู้รับรู้สึกกลัวสุดขีด',
    canUseWith: [],
    neverUseWith: ['everyone — this is illegal'],
    alternatives: ['I\'m really angry', 'I need to talk to an adult', 'please leave me alone'],
    impactDescription: 'เป็นการคุกคามที่ผิดกฎหมาย ทำให้ผู้ถูกขู่กลัวสำหรับความปลอดภัยของตัวเอง',
    hasDangerFlag: true,
  },
  {
    word: 'i will hurt you', lang: 'en',
    exampleTh: '"จะทำร้ายแก!" — ขู่ว่าจะทำร้ายร่างกาย เป็นอาชญากรรม',
    exampleEn: '"I will hurt you!"',
    severityExplanation: 'การขู่ทำร้ายร่างกายซึ่งเป็นความผิดทางกฎหมาย',
    canUseWith: [],
    neverUseWith: ['everyone — this is illegal'],
    alternatives: ['I need to calm down', 'tell a trusted adult', 'remove yourself from the situation'],
    impactDescription: 'ทำให้ผู้ถูกขู่ต้องอยู่ในความกลัวและอาจต้องขอความช่วยเหลือจากตำรวจ',
    hasDangerFlag: true,
  },
  {
    word: 'harassment', lang: 'en',
    exampleTh: 'การคุกคามซ้ำๆ เช่น ส่งข้อความรบกวนทุกวัน หรือแกล้งคนซ้ำๆ',
    exampleEn: 'Sending repeated unwanted messages or following someone is harassment.',
    severityExplanation: 'การคุกคามซ้ำๆ ที่ทำให้คนรู้สึกไม่ปลอดภัย เป็นผิดกฎหมาย',
    canUseWith: [],
    neverUseWith: ['everyone — never engage in this behavior'],
    alternatives: ['respect others\' boundaries', 'if someone says stop, stop', 'talk to an adult for help'],
    impactDescription: 'ทำให้ผู้ถูกคุกคามรู้สึกไม่ปลอดภัยและเครียดทุกวัน',
    hasDangerFlag: true,
  },
  {
    word: 'bully', lang: 'en',
    exampleTh: 'การรังแกคนอ่อนแอกว่าซ้ำๆ ทั้งในชีวิตจริงและออนไลน์',
    exampleEn: 'Repeatedly picking on someone weaker is bullying.',
    severityExplanation: 'การรังแกที่ทำร้ายจิตใจและร่างกายซ้ำๆ เป็นพฤติกรรมที่ยอมรับไม่ได้',
    canUseWith: [],
    neverUseWith: ['everyone — never bully'],
    alternatives: ['be kind', 'stand up for others', 'tell a trusted adult if you see bullying'],
    impactDescription: 'ทำให้ผู้ถูกรังแกเกิดปัญหาสุขภาพจิตระยะยาวและกลัวการไปโรงเรียน',
    hasDangerFlag: true,
  },
  {
    word: 'threat', lang: 'en',
    exampleTh: 'การขู่ว่าจะทำสิ่งแย่ๆ เพื่อให้คนอื่นทำตาม',
    exampleEn: '"Do it or I\'ll tell everyone your secret." — this is a threat.',
    severityExplanation: 'การขู่เป็นความผิดทางกฎหมายและทำให้คนรู้สึกกลัว',
    canUseWith: [],
    neverUseWith: ['everyone — threatening is illegal'],
    alternatives: ['ask nicely', 'explain your feelings', 'let an adult help resolve it'],
    impactDescription: 'ทำให้ผู้ถูกขู่รู้สึกว่าไม่มีทางเลือกและต้องอยู่ในความกลัว',
    hasDangerFlag: true,
  },
  {
    word: 'cyberbully', lang: 'en',
    exampleTh: 'การรังแกออนไลน์ เช่น โพสต์รูปล้อเลียน ส่งข้อความด่าทอ หรือแบนจากกลุ่ม',
    exampleEn: 'Posting mean things about someone online is cyberbullying.',
    severityExplanation: 'การรังแกผ่านอินเทอร์เน็ต ร้ายแรงเพราะคนอื่นเห็นได้มากมาย',
    canUseWith: [],
    neverUseWith: ['everyone — never cyberbully'],
    alternatives: ['block and report', 'screenshot for evidence', 'tell a trusted adult immediately'],
    impactDescription: 'ทำให้ผู้ถูกรังแกรู้สึกอับอายต่อหน้าคนจำนวนมากและหนีไปไหนไม่ได้',
    hasDangerFlag: true,
  },
  {
    word: 'stalk', lang: 'en',
    exampleTh: 'การติดตามหรือสอดส่องคนโดยไม่ได้รับอนุญาต ทั้งในชีวิตจริงและออนไลน์',
    exampleEn: 'Checking someone\'s location without permission is stalking.',
    severityExplanation: 'การติดตามคุกคามเป็นอาชญากรรมร้ายแรงที่ทำให้ผู้ถูกกระทำรู้สึกไม่ปลอดภัย',
    canUseWith: [],
    neverUseWith: ['everyone — this is illegal'],
    alternatives: ['respect privacy', 'if you\'re worried about someone tell an adult', 'contact them through proper channels'],
    impactDescription: 'ทำให้ผู้ถูกสะกดรอยกลัวสำหรับความปลอดภัยตลอดเวลา',
    hasDangerFlag: true,
  },
  {
    word: 'i know where you live', lang: 'en',
    exampleTh: '"ฉันรู้ว่าแกอยู่ที่ไหน" — ขู่เปิดเผยที่อยู่ เป็นอาชญากรรมร้ายแรง',
    exampleEn: '"I know where you live!" (as a threat)',
    severityExplanation: 'เป็นการขู่ที่อันตรายอย่างยิ่ง ทำให้ผู้รับรู้สึกว่าบ้านของตัวเองไม่ปลอดภัย',
    canUseWith: [],
    neverUseWith: ['everyone — this is a serious threat'],
    alternatives: ['never say this', 'tell a trusted adult if someone says this to you', 'call for help immediately'],
    impactDescription: 'ทำให้ผู้ถูกขู่รู้สึกไม่ปลอดภัยแม้แต่ที่บ้านของตัวเอง',
    hasDangerFlag: true,
  },

  // ─── TH Level 1 — สุภาพ ─────────────────────────────────────────────────────
  {
    word: 'ขอบคุณ', lang: 'th',
    exampleTh: '"ขอบคุณมากนะที่ช่วยหยิบของให้!" — แสดงความซาบซึ้งใจ',
    exampleEn: '"Thank you so much for helping!"',
    severityExplanation: 'คำขอบคุณที่ทำให้อีกฝ่ายรู้ว่าความพยายามของเขาได้รับการมองเห็น',
    canUseWith: ['ทุกคน'],
    neverUseWith: [],
    alternatives: [],
    impactDescription: 'ทำให้คนรู้สึกมีคุณค่าและสร้างความสัมพันธ์ที่ดี',
    hasDangerFlag: false,
  },
  {
    word: 'ขอโทษ', lang: 'th',
    exampleTh: '"ขอโทษที่ทำแก้วแตก ฉันไม่ได้ตั้งใจ"',
    exampleEn: '"I\'m sorry I broke the glass, I didn\'t mean to."',
    severityExplanation: 'การขอโทษที่จริงใจช่วยซ่อมแซมความสัมพันธ์',
    canUseWith: ['ทุกคน'],
    neverUseWith: [],
    alternatives: ['เสียใจมากที่เกิดเรื่องนี้', 'ฉันผิดเอง'],
    impactDescription: 'ลดความขัดแย้งและแสดงว่าเราใส่ใจความรู้สึกของคนอื่น',
    hasDangerFlag: false,
  },
  {
    word: 'สวัสดี', lang: 'th',
    exampleTh: '"สวัสดีครับ/ค่ะ!" — ทักทายอย่างสุภาพ',
    exampleEn: '"Hello! / Hi there!"',
    severityExplanation: 'คำทักทายที่เปิดการสื่อสารอย่างอบอุ่นและเป็นมิตร',
    canUseWith: ['ทุกคน'],
    neverUseWith: [],
    alternatives: ['หวัดดี (ระหว่างเพื่อน)', 'ดีครับ/ค่ะ'],
    impactDescription: 'สร้างบรรยากาศที่เป็นมิตรตั้งแต่เริ่มต้น',
    hasDangerFlag: false,
  },
  {
    word: 'กรุณา', lang: 'th',
    exampleTh: '"กรุณาส่งสมุดให้หน่อยได้ไหมคะ?"',
    exampleEn: '"Could you please pass me the notebook?"',
    severityExplanation: 'คำขอร้องสุภาพที่ทำให้อีกฝ่ายอยากช่วยเหลือ',
    canUseWith: ['ทุกคน'],
    neverUseWith: [],
    alternatives: ['ช่วย...หน่อยได้ไหม', 'ขอ...หน่อยนะ'],
    impactDescription: 'ทำให้การขอร้องฟังดูสุภาพและไม่เป็นการบังคับ',
    hasDangerFlag: false,
  },
  {
    word: 'ยินดีต้อนรับ', lang: 'th',
    exampleTh: '"ยินดีต้อนรับสู่บ้านของเรานะคะ!"',
    exampleEn: '"Welcome to our home!"',
    severityExplanation: 'ทำให้ผู้มาเยือนรู้สึกว่าตัวเองได้รับการต้อนรับและเป็นที่ต้องการ',
    canUseWith: ['ทุกคน'],
    neverUseWith: [],
    alternatives: ['ขอต้อนรับ', 'เชิญเลย'],
    impactDescription: 'ทำให้คนรู้สึกสบายใจและเป็นที่ยอมรับ',
    hasDangerFlag: false,
  },
  {
    word: 'ขอบใจ', lang: 'th',
    exampleTh: '"ขอบใจนะที่รอ!" — ใช้กับเพื่อนสนิทหรือคนที่สนิทกัน',
    exampleEn: '"Thanks for waiting!"',
    severityExplanation: 'คำขอบคุณแบบเป็นกันเอง เหมาะกับเพื่อนและคนที่รู้จักดี',
    canUseWith: ['เพื่อน', 'พี่น้อง', 'คนที่สนิท'],
    neverUseWith: ['ครู', 'ผู้ใหญ่ที่ไม่สนิท'],
    alternatives: ['ขอบคุณ (ทางการกว่า)'],
    impactDescription: 'สร้างความใกล้ชิดในมิตรภาพ',
    hasDangerFlag: false,
  },
  {
    word: 'เก่งมาก', lang: 'th',
    exampleTh: '"เก่งมากเลย! สอบได้ A อีกแล้ว!"',
    exampleEn: '"Great job! You got an A again!"',
    severityExplanation: 'คำชมเชยที่ให้กำลังใจและสร้างความมั่นใจ',
    canUseWith: ['ทุกคน'],
    neverUseWith: [],
    alternatives: ['ยอดเยี่ยม', 'ดีมากๆ', 'สุดยอด'],
    impactDescription: 'ทำให้คนรู้สึกภูมิใจและมีแรงบันดาลใจ',
    hasDangerFlag: false,
  },
  {
    word: 'ดีใจด้วย', lang: 'th',
    exampleTh: '"ดีใจด้วยนะที่ชนะการแข่งขัน!"',
    exampleEn: '"Congratulations on winning the competition!"',
    severityExplanation: 'แสดงความยินดีกับความสำเร็จของคนอื่น ทำให้รู้สึกว่าคนอื่นใส่ใจ',
    canUseWith: ['ทุกคน'],
    neverUseWith: [],
    alternatives: ['ยินดีด้วย', 'สุดยอดเลย', 'เก่งมาก'],
    impactDescription: 'ทำให้ความสำเร็จมีความหมายมากขึ้นเมื่อมีคนร่วมยินดี',
    hasDangerFlag: false,
  },

  // ─── TH Level 2 — ไม่สุภาพ ──────────────────────────────────────────────────
  {
    word: 'โง่', lang: 'th',
    exampleTh: '"โง่จังเลย!" — ดูถูกความฉลาด ทำให้อีกฝ่ายรู้สึกอับอาย',
    exampleEn: '"That\'s so dumb!"',
    severityExplanation: 'ดูถูกความฉลาดของคน ทำให้รู้สึกอับอายและไม่มั่นใจ',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['คิดไม่ทัน', 'ยังไม่เข้าใจ', 'ช่วยอธิบายอีกทีได้ไหม'],
    impactDescription: 'ทำให้คนกลัวที่จะแสดงความคิดเห็นหรือถามคำถาม',
    hasDangerFlag: false,
  },
  {
    word: 'เงียบ!', lang: 'th',
    exampleTh: '"เงียบ! ฉันกำลังดูอยู่!" — บอกให้หยุดพูดอย่างหยาบคาย',
    exampleEn: '"Be quiet! I\'m watching!"',
    severityExplanation: 'สั่งให้หยุดพูดโดยไม่สุภาพ ทำให้อีกฝ่ายรู้สึกถูกปฏิเสธ',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ช่วยเงียบหน่อยได้ไหม', 'ขอเวลาสักครู่', 'คุยทีหลังได้ไหม'],
    impactDescription: 'ทำให้อีกฝ่ายรู้สึกถูกดูถูกและไม่อยากพูดอีก',
    hasDangerFlag: false,
  },
  {
    word: 'ขี้โกหก', lang: 'th',
    exampleTh: '"ขี้โกหก! ไม่ได้เป็นอย่างนั้น!" — กล่าวหาว่าโกหกโดยตรง',
    exampleEn: '"You\'re lying!"',
    severityExplanation: 'กล่าวหาว่าโกหก ทำลายความน่าเชื่อถือของคน',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ฉันไม่แน่ใจว่าถูก', 'ช่วยอธิบายอีกทีได้ไหม', 'ฉันจำไม่เหมือนกัน'],
    impactDescription: 'ทำลายความไว้วางใจและความสัมพันธ์',
    hasDangerFlag: false,
  },
  {
    word: 'น่ารำคาญ', lang: 'th',
    exampleTh: '"น่ารำคาญมากเลย!" — บอกว่าคนหรือพฤติกรรมของเขาทำให้หงุดหงิด',
    exampleEn: '"You\'re so annoying!"',
    severityExplanation: 'ดูถูกพฤติกรรมของคน ทำให้รู้สึกว่าตัวเองไม่เป็นที่ต้องการ',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ฉันต้องการเวลาคนเดียวหน่อย', 'คุยกันทีหลังได้ไหม'],
    impactDescription: 'ทำให้คนรู้สึกไม่เป็นที่ต้องการและไม่มั่นใจในตัวเอง',
    hasDangerFlag: false,
  },
  {
    word: 'แหย่', lang: 'th',
    exampleTh: '"แหย่ให้แกโกรธเล่นๆ นะ" — แกล้งหรือล้อเพื่อความสนุก ทำให้อีกฝ่ายไม่พอใจ',
    exampleEn: '"I was just teasing you!"',
    severityExplanation: 'การล้อที่ทำให้คนรู้สึกไม่ดี แม้จะทำเพื่อความสนุกก็ตาม',
    canUseWith: [],
    neverUseWith: ['คนที่ไม่ชอบการล้อเล่น', 'เรื่องที่อ่อนไหว'],
    alternatives: ['เล่นด้วยกันแบบอื่น', 'ถามก่อนว่าเขาชอบการล้อไหม'],
    impactDescription: 'ทำให้คนที่ถูกแหย่รู้สึกไม่ปลอดภัยและไม่สนุก',
    hasDangerFlag: false,
  },
  {
    word: 'เบื่อ', lang: 'th',
    exampleTh: '"เบื่อแกมากเลย!" — แสดงว่าเบื่อหน่ายคนอื่น ดูถูก',
    exampleEn: '"You bore me."',
    severityExplanation: 'แสดงความเบื่อหน่ายต่อคนอื่น ทำให้รู้สึกว่าตัวเองน่าเบื่อ',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ฉันอยากลองทำอะไรใหม่', 'ลองเล่นอย่างอื่นกันดีกว่า'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองไม่น่าสนใจและไม่เป็นที่ต้องการ',
    hasDangerFlag: false,
  },
  {
    word: 'ไม่สน', lang: 'th',
    exampleTh: '"ไม่สนหรอก!" — แสดงว่าไม่สนใจสิ่งที่อีกฝ่ายพูดหรือรู้สึก',
    exampleEn: '"I don\'t care."',
    severityExplanation: 'แสดงว่าไม่ใส่ใจความรู้สึกหรือความคิดเห็นของคนอื่น',
    canUseWith: [],
    neverUseWith: ['เพื่อนที่เล่าเรื่องสำคัญ', 'คนที่ต้องการความช่วยเหลือ'],
    alternatives: ['ฉันกำลังฟังอยู่', 'ขอโทษที่ไม่ได้ตั้งใจ'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองไม่สำคัญ',
    hasDangerFlag: false,
  },
  {
    word: 'หน้าเบื่อ', lang: 'th',
    exampleTh: '"แกหน้าเบื่อมากเลย!" — เรียกคนว่าน่าเบื่อ ดูถูกบุคลิก',
    exampleEn: '"You have such a boring face."',
    severityExplanation: 'ดูถูกบุคลิกและรูปหน้าของคน ทำให้รู้สึกไม่มั่นใจ',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ลองทำอะไรสนุกๆ ด้วยกัน', 'คุณมีเรื่องอะไรน่าเล่าไหม'],
    impactDescription: 'ทำให้คนรู้สึกอับอายในบุคลิกของตัวเอง',
    hasDangerFlag: false,
  },

  // ─── TH Level 3 — หยาบ ──────────────────────────────────────────────────────
  {
    word: 'ไอ้', lang: 'th',
    exampleTh: '"ไอ้นั่น!" — คำนำหน้าดูถูกผู้ชาย ทำให้รู้สึกถูกดูถูก',
    exampleEn: '"Hey you!" (disrespectfully)',
    severityExplanation: 'คำนำหน้าที่ดูถูกคนชาย ใช้ในบริบทที่ไม่เป็นมิตร',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ชื่อจริง', 'เพื่อน', 'น้อง/พี่'],
    impactDescription: 'ทำให้คนรู้สึกถูกดูถูกและไม่ได้รับการเคารพ',
    hasDangerFlag: false,
  },
  {
    word: 'อีแม่', lang: 'th',
    exampleTh: '"อีแม่แก!" — คำด่าหยาบคายที่ดูถูกผู้หญิง',
    exampleEn: '"(vulgar insult for women)"',
    severityExplanation: 'คำหยาบคายมากที่ดูถูกผู้หญิง ไม่ควรใช้ในทุกกรณี',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ชื่อจริง', 'หยุดพูดคุยหากโกรธ', 'บอกผู้ใหญ่'],
    impactDescription: 'ทำให้ผู้หญิงรู้สึกถูกดูถูกและอับอายอย่างรุนแรง',
    hasDangerFlag: false,
  },
  {
    word: 'งี่เง่า', lang: 'th',
    exampleTh: '"งี่เง่ามากเลย!" — บอกว่าคนหรือสิ่งที่ทำนั้นไม่ฉลาด',
    exampleEn: '"That\'s so silly / stupid!"',
    severityExplanation: 'ดูถูกความฉลาดหรือการตัดสินใจของคน',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ลองคิดใหม่ดีกว่า', 'มีวิธีที่ดีกว่านี้นะ'],
    impactDescription: 'ทำให้คนรู้สึกว่าความคิดของตัวเองไม่มีคุณค่า',
    hasDangerFlag: false,
  },
  {
    word: 'ขยะ', lang: 'th',
    exampleTh: '"แกเป็นขยะ!" — เรียกคนว่าไร้ค่าเหมือนขยะ',
    exampleEn: '"You\'re trash!"',
    severityExplanation: 'ดูถูกคนอย่างรุนแรงว่าไม่มีคุณค่า',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ฉันไม่เห็นด้วย', 'ฉันรู้สึกไม่ดีกับสิ่งที่เกิดขึ้น'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองไร้คุณค่าและไม่มีความหมาย',
    hasDangerFlag: false,
  },
  {
    word: 'ตัวร้าย', lang: 'th',
    exampleTh: '"แกเป็นตัวร้าย!" — เรียกคนว่าเป็นคนเลวหรือตัวร้าย',
    exampleEn: '"You\'re the villain!"',
    severityExplanation: 'ตัดสินคนว่าเป็นคนเลว ทำลายภาพลักษณ์',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ฉันไม่ชอบสิ่งที่แกทำ', 'พฤติกรรมนั้นไม่ดี'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองถูกตัดสินและไม่มีโอกาสแก้ตัว',
    hasDangerFlag: false,
  },
  {
    word: 'ขี้เกียจ', lang: 'th',
    exampleTh: '"ขี้เกียจมากเลย!" — ดูถูกว่าคนไม่ขยัน',
    exampleEn: '"You\'re so lazy!"',
    severityExplanation: 'ดูถูกความพยายามของคน อาจไม่รู้ว่าเขามีปัญหาอื่น',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ต้องการความช่วยเหลือไหม', 'มีอะไรให้ช่วยได้ไหม'],
    impactDescription: 'ทำให้คนรู้สึกผิดและอับอาย อาจซ่อนปัญหาสุขภาพหรืออารมณ์อยู่',
    hasDangerFlag: false,
  },
  {
    word: 'น่าเกลียด', lang: 'th',
    exampleTh: '"หน้าน่าเกลียดมาก!" — ดูถูกรูปลักษณ์ภายนอก',
    exampleEn: '"You\'re so ugly!"',
    severityExplanation: 'ดูถูกรูปลักษณ์ที่คนควบคุมไม่ได้ ทำร้ายความมั่นใจอย่างรุนแรง',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ทุกคนสวยแบบของตัวเอง', 'ความสวยมีหลายแบบ'],
    impactDescription: 'ทำให้คนไม่มั่นใจในรูปลักษณ์และอาจนำไปสู่ปัญหาภาพลักษณ์',
    hasDangerFlag: false,
  },
  {
    word: 'อ้วน', lang: 'th',
    exampleTh: '"อ้วนมากเลยนะ!" — ดูถูกน้ำหนักหรือร่างกาย',
    exampleEn: '"You\'re so fat!"',
    severityExplanation: 'ดูถูกร่างกายของคน อาจนำไปสู่ปัญหาสุขภาพจิตและการกิน',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ทุกร่างกายมีความสวยงาม', 'สุขภาพสำคัญกว่าขนาด'],
    impactDescription: 'ทำให้คนรู้สึกอับอายในร่างกายตัวเองและอาจนำไปสู่การอดอาหารหรือซึมเศร้า',
    hasDangerFlag: false,
  },

  // ─── TH Level 4 — รุนแรง ────────────────────────────────────────────────────
  {
    word: 'ไปตาย', lang: 'th',
    exampleTh: '"ไปตายซะ!" — บอกให้คนตาย อันตรายมากและผิดกฎหมาย',
    exampleEn: '"Go die!"',
    severityExplanation: 'อันตรายมาก อาจกระตุ้นให้คนคิดทำร้ายตัวเอง',
    canUseWith: [],
    neverUseWith: ['ทุกคน — ห้ามพูดเด็ดขาด'],
    alternatives: ['ฉันโกรธมาก', 'ฉันต้องการพื้นที่ส่วนตัว', 'บอกผู้ใหญ่'],
    impactDescription: 'อาจทำให้คนคิดฆ่าตัวตายและเป็นการขู่ที่ผิดกฎหมาย',
    hasDangerFlag: true,
  },
  {
    word: 'เกลียด', lang: 'th',
    exampleTh: '"เกลียดแกมาก!" — แสดงความเกลียดชังโดยตรง',
    exampleEn: '"I hate you!"',
    severityExplanation: 'แสดงความเกลียดชังรุนแรง ทำให้คนรู้สึกว่าไม่เป็นที่รัก',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ฉันโกรธมากตอนนี้', 'ฉันต้องการเวลาคิด', 'สิ่งที่แกทำทำให้ฉันเจ็บปวด'],
    impactDescription: 'ทำให้คนรู้สึกถูกปฏิเสธและไม่มีคุณค่า อาจส่งผลระยะยาว',
    hasDangerFlag: true,
  },
  {
    word: 'หน้าหนา', lang: 'th',
    exampleTh: '"หน้าหนามากนะ!" — บอกว่าคนหน้าด้าน ไม่รู้จักอาย',
    exampleEn: '"You have no shame!"',
    severityExplanation: 'ดูถูกบุคลิกและการกระทำของคนอย่างรุนแรง',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ฉันรู้สึกไม่สบายใจกับสิ่งที่เกิดขึ้น', 'คุยกันดีๆ ได้ไหม'],
    impactDescription: 'ทำให้คนรู้สึกอับอายและถูกตัดสิน',
    hasDangerFlag: true,
  },
  {
    word: 'ขี้แพ้', lang: 'th',
    exampleTh: '"ขี้แพ้มาก! แพ้แล้วร้องไห้!" — ดูถูกคนที่แพ้หรือแสดงอารมณ์',
    exampleEn: '"You\'re such a sore loser!"',
    severityExplanation: 'ดูถูกคนว่าแพ้และอ่อนแอ ทำให้ไม่กล้าแสดงความรู้สึก',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['สู้ต่อไปนะ', 'ครั้งหน้าทำได้แน่', 'เป็นเรื่องปกติที่จะแพ้บ้าง'],
    impactDescription: 'ทำให้คนรู้สึกว่าการแพ้เป็นเรื่องน่าอับอายและไม่กล้าพยายามอีก',
    hasDangerFlag: true,
  },
  {
    word: 'สัตว์', lang: 'th',
    exampleTh: '"สัตว์มากเลย!" — ด่าคนว่าเป็นสัตว์ แสดงความดูถูกอย่างรุนแรง',
    exampleEn: '"You\'re an animal!" (as an insult)',
    severityExplanation: 'คำด่าที่ดูถูกคนอย่างรุนแรง เปรียบเทียบกับสัตว์',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['ฉันไม่พอใจในสิ่งที่เกิดขึ้น', 'บอกผู้ใหญ่'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองถูกลดคุณค่าความเป็นมนุษย์',
    hasDangerFlag: true,
  },
  {
    word: 'ไอ้ขยะ', lang: 'th',
    exampleTh: '"ไอ้ขยะ!" — รวมคำดูถูกหลายอย่างเข้าด้วยกัน รุนแรงมาก',
    exampleEn: '"You piece of trash!"',
    severityExplanation: 'คำด่าที่รุนแรงมาก ดูถูกคนว่าไม่มีคุณค่าเลย',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['หยุดทะเลาะ', 'บอกผู้ใหญ่', 'ออกจากสถานการณ์นั้น'],
    impactDescription: 'ทำให้คนรู้สึกว่าตัวเองไม่มีคุณค่าอย่างสมบูรณ์',
    hasDangerFlag: true,
  },
  {
    word: 'หน้าตาย', lang: 'th',
    exampleTh: '"หน้าตายมากเลย!" — ดูถูกการแสดงออกทางสีหน้าของคน',
    exampleEn: '"You look dead inside!"',
    severityExplanation: 'ดูถูกบุคลิกของคนอย่างรุนแรง',
    canUseWith: [],
    neverUseWith: ['ทุกคน'],
    alternatives: ['แกเป็นยังไงบ้าง?', 'มีอะไรให้ช่วยไหม'],
    impactDescription: 'ทำให้คนรู้สึกอับอายในบุคลิกและการแสดงออกของตัวเอง',
    hasDangerFlag: true,
  },

  // ─── TH Level 5 — อันตราย ───────────────────────────────────────────────────
  {
    word: 'ฆ่าแก', lang: 'th',
    exampleTh: '"จะฆ่าแก!" — ขู่ฆ่า เป็นอาชญากรรม ต้องแจ้งผู้ใหญ่ทันที',
    exampleEn: '"I\'ll kill you!" (as a threat)',
    severityExplanation: 'การขู่ฆ่าเป็นความผิดทางกฎหมายและทำให้ผู้รับรู้สึกกลัวสุดขีด',
    canUseWith: [],
    neverUseWith: ['ทุกคน — ผิดกฎหมาย'],
    alternatives: ['ฉันโกรธมาก ต้องการความช่วยเหลือ', 'แจ้งผู้ใหญ่ทันที', 'โทร 191'],
    impactDescription: 'เป็นอาชญากรรม ทำให้ผู้ถูกขู่กลัวสำหรับชีวิต',
    hasDangerFlag: true,
  },
  {
    word: 'ทำร้าย', lang: 'th',
    exampleTh: '"จะทำร้ายแก!" — ขู่ว่าจะทำร้ายร่างกาย เป็นอาชญากรรม',
    exampleEn: '"I\'ll hurt you!"',
    severityExplanation: 'การขู่ทำร้ายเป็นความผิดทางกฎหมาย',
    canUseWith: [],
    neverUseWith: ['ทุกคน — ผิดกฎหมาย'],
    alternatives: ['บอกผู้ใหญ่', 'ออกจากสถานการณ์', 'โทร 191'],
    impactDescription: 'ทำให้ผู้ถูกขู่ต้องอยู่ในความกลัวและต้องขอความช่วยเหลือ',
    hasDangerFlag: true,
  },
  {
    word: 'แกล้ง', lang: 'th',
    exampleTh: 'การจงใจทำให้คนเจ็บปวดซ้ำๆ ทั้งร่างกายและจิตใจ',
    exampleEn: 'Intentionally hurting someone repeatedly.',
    severityExplanation: 'การแกล้งซ้ำๆ คือการรังแก ซึ่งเป็นพฤติกรรมที่ยอมรับไม่ได้',
    canUseWith: [],
    neverUseWith: ['ทุกคน — ห้ามทำ'],
    alternatives: ['เล่นด้วยกันอย่างสนุกสนาน', 'ถามว่าเขาโอเคไหม', 'บอกผู้ใหญ่ถ้าเห็นการแกล้ง'],
    impactDescription: 'ทำให้ผู้ถูกแกล้งกลัวและเครียดทุกวัน อาจนำไปสู่ปัญหาสุขภาพจิตระยะยาว',
    hasDangerFlag: true,
  },
  {
    word: 'คุกคาม', lang: 'th',
    exampleTh: 'การส่งข้อความหรือทำพฤติกรรมที่ทำให้คนรู้สึกไม่ปลอดภัยซ้ำๆ',
    exampleEn: 'Repeatedly messaging or following someone who asked you to stop.',
    severityExplanation: 'การคุกคามเป็นผิดกฎหมายและทำให้ผู้ถูกกระทำรู้สึกไม่ปลอดภัย',
    canUseWith: [],
    neverUseWith: ['ทุกคน — ผิดกฎหมาย'],
    alternatives: ['เคารพขอบเขตของคนอื่น', 'หยุดเมื่อเขาบอกหยุด', 'บอกผู้ใหญ่ถ้าถูกคุกคาม'],
    impactDescription: 'ทำให้ผู้ถูกคุกคามรู้สึกไม่ปลอดภัยและต้องการความช่วยเหลือ',
    hasDangerFlag: true,
  },
  {
    word: 'ตามล่า', lang: 'th',
    exampleTh: 'การสะกดรอยหรือติดตามคนโดยไม่ได้รับอนุญาต',
    exampleEn: 'Following or tracking someone without their knowledge.',
    severityExplanation: 'การสะกดรอยเป็นอาชญากรรมที่ทำให้ผู้ถูกกระทำรู้สึกไม่ปลอดภัย',
    canUseWith: [],
    neverUseWith: ['ทุกคน — ผิดกฎหมาย'],
    alternatives: ['เคารพความเป็นส่วนตัว', 'ถ้าเป็นห่วงใครบอกผู้ใหญ่', 'โทร 191 ถ้าอยู่ในอันตราย'],
    impactDescription: 'ทำให้ผู้ถูกสะกดรอยกลัวตลอดเวลาแม้แต่ในที่สาธารณะ',
    hasDangerFlag: true,
  },
  {
    word: 'ขู่กรรโชก', lang: 'th',
    exampleTh: 'การขู่ว่าจะทำสิ่งแย่ๆ เพื่อบังคับให้คนทำตามหรือจ่ายเงิน',
    exampleEn: '"Pay me or I\'ll tell everyone your secret." — this is extortion.',
    severityExplanation: 'การกรรโชกทรัพย์เป็นอาชญากรรมร้ายแรงในไทย',
    canUseWith: [],
    neverUseWith: ['ทุกคน — ผิดกฎหมาย'],
    alternatives: ['ขอความช่วยเหลือจากผู้ใหญ่', 'แจ้งตำรวจ', 'ไม่ยอมทำตาม'],
    impactDescription: 'ทำให้ผู้ถูกขู่รู้สึกหมดทางเลือกและต้องอยู่ในความกลัว',
    hasDangerFlag: true,
  },
  {
    word: 'ทำโทษ', lang: 'th',
    exampleTh: '"จะทำโทษแก!" — ขู่ว่าจะลงโทษ บังคับด้วยความกลัว',
    exampleEn: '"I will punish you!" (as a threat)',
    severityExplanation: 'การขู่ว่าจะลงโทษเพื่อบังคับให้ทำตามถือเป็นการคุกคาม',
    canUseWith: [],
    neverUseWith: ['ทุกคน — ห้ามขู่'],
    alternatives: ['คุยกันดีๆ', 'บอกผู้ใหญ่', 'ออกจากสถานการณ์'],
    impactDescription: 'ทำให้คนรู้สึกกลัวและถูกบังคับ ไม่ใช่การสื่อสารที่ดี',
    hasDangerFlag: true,
  },
]
